owner: nanangsb # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Quran Abu Sofiya
    url: https://quran.abusofiya.com
  - name: Zikir V1
    url: https://zikir.org
  - name: Zikir V2
    url: https://v2.zikir.org
  - name: Api Artikel Islami
    url: https://api-artikel.abusofiya.com/api
  - name: Api Artikel Islami V2
    url: https://api-artikel2.abusofiya.com/api/news/source?code=MUSLIM
  - name: Kajian.co
    url: https://kajian.co
  - name: Quran Site
    url: https://quransite.com
  - name: Majemuk
    url: https://majemuk.com
  - name: Infigur
    url: https://infigur.com
  - name: Tool Unity
    url: https://toolunity.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
 # apiBaseUrl: https://api.github.com
  workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/1 * * * *"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
